#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
AAR="$ROOT/app/libs/ffmpeg-kit-full-gpl-6.0-2.LTS.aar"
JNILIBS="$ROOT/app/src/main/jniLibs"
INCLUDE="$ROOT/app/src/main/cpp/include"
ABIS=(arm64-v8a x86_64)
LIBS=(avcodec avformat avutil swresample swscale)

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# The aar's FFmpeg libs declare NEEDED libc++_shared.so, so its copy ships alongside them.
for abi in "${ABIS[@]}"; do
  mkdir -p "$JNILIBS/$abi"
  for lib in "${LIBS[@]}" c++_shared; do
    unzip -o -j -q "$AAR" "jni/$abi/lib$lib.so" -d "$JNILIBS/$abi"
  done
done

if [ ! -f "$INCLUDE/libavformat/avformat.h" ]; then
  curl -fsSL https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz -o "$tmp/ffmpeg.tar.xz"
  tar -xf "$tmp/ffmpeg.tar.xz" -C "$tmp"
  src="$tmp/ffmpeg-6.0"
  for lib in "${LIBS[@]}"; do
    mkdir -p "$INCLUDE/lib$lib"
    (cd "$src/lib$lib" && find . -maxdepth 1 -name '*.h' -exec cp {} "$INCLUDE/lib$lib/" \;)
  done
  # avconfig.h is generated by FFmpeg's configure; both target ABIs are little-endian.
  cat > "$INCLUDE/libavutil/avconfig.h" <<'H'
#ifndef AVUTIL_AVCONFIG_H
#define AVUTIL_AVCONFIG_H
#define AV_HAVE_BIGENDIAN 0
#define AV_HAVE_FAST_UNALIGNED 1
#endif
H
  echo '#define FFMPEG_VERSION "6.0"' > "$INCLUDE/libavutil/ffversion.h"
fi
echo "FFmpeg libs and headers ready."
