#!/usr/bin/env bash
# Downloads the FFmpeg 6.0 public headers matching the prebuilt libs in app/src/main/jniLibs
# (ffmpeg-kit 6.0-2.LTS full-gpl).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INCLUDE="$ROOT/app/src/main/cpp/include"
LIBS=(avcodec avformat avutil swresample swscale)

if [ -f "$INCLUDE/libavformat/avformat.h" ]; then
  echo "FFmpeg headers already present."
  exit 0
fi

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
curl -fsSL https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz -o "$tmp/ffmpeg.tar.xz"
tar -xf "$tmp/ffmpeg.tar.xz" -C "$tmp"
src="$tmp/ffmpeg-6.0"
for lib in "${LIBS[@]}"; do
  mkdir -p "$INCLUDE/lib$lib"
  (cd "$src/lib$lib" && find . -maxdepth 1 -name '*.h' -exec cp {} "$INCLUDE/lib$lib/" \;)
done
# avconfig.h is generated by FFmpeg's configure; both target ABIs are little-endian.
cat > "$INCLUDE/libavutil/avconfig.h" <<'H'
#ifndef AVUTIL_AVCONFIG_H
#define AVUTIL_AVCONFIG_H
#define AV_HAVE_BIGENDIAN 0
#define AV_HAVE_FAST_UNALIGNED 1
#endif
H
echo '#define FFMPEG_VERSION "6.0"' > "$INCLUDE/libavutil/ffversion.h"
echo "FFmpeg headers ready."
